apiVersion: v1
kind: Service
metadata:
  labels:
    app: kafka-connect
  name: kafka-connect
spec:
  ports:
    - port: 8083
      targetPort: 8083
  selector:
    app: kafka-connect
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: kafka-connect
  name: kafka-connect
spec:
  replicas: 2
  selector:
    matchLabels:
      app: kafka-connect
  template:
    metadata:
      labels:
        app: kafka-connect
    spec:
      containers:
        - image: kafka-connect:2.8.1
          name: kafka-connect-container
          ports:
            - containerPort: 8083
          envFrom:
            - secretRef:
                name: aws-creds
          volumeMounts:
            - name: connect-props-volume
              mountPath: /opt/bitnami/kafka/config
          resources: {}
          imagePullPolicy: Never # shouldn't be Always
      volumes:
        - name: connect-props-volume
          configMap:
            name: connect-props
